/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppNewRouteImport } from './routes/_app/new'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppDocumentsDocumentIdRouteImport } from './routes/_app/documents.$documentId'
import { Route as AppSilosSiloIdConfigRouteImport } from './routes/_app/silos.$siloId.config'
import { Route as AppSilosSiloIdNewRouteImport } from './routes/_app/silos.$siloId.new'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsDocumentIdRoute = AppDocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => AppRoute,
} as any)
const AppSilosSiloIdConfigRoute = AppSilosSiloIdConfigRouteImport.update({
  id: '/silos/$siloId/config',
  path: '/silos/$siloId/config',
  getParentRoute: () => AppRoute,
} as any)
const AppSilosSiloIdNewRoute = AppSilosSiloIdNewRouteImport.update({
  id: '/silos/$siloId/new',
  path: '/silos/$siloId/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/history': typeof AppHistoryRoute
  '/new': typeof AppNewRoute
  '/users': typeof AppUsersRoute
  '/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/silos/$siloId/config': typeof AppSilosSiloIdConfigRoute
  '/silos/$siloId/new': typeof AppSilosSiloIdNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/history': typeof AppHistoryRoute
  '/new': typeof AppNewRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/silos/$siloId/config': typeof AppSilosSiloIdConfigRoute
  '/silos/$siloId/new': typeof AppSilosSiloIdNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/new': typeof AppNewRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/_app/silos/$siloId/config': typeof AppSilosSiloIdConfigRoute
  '/_app/silos/$siloId/new': typeof AppSilosSiloIdNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/history'
    | '/new'
    | '/users'
    | '/documents/$documentId'
    | '/silos/$siloId/config'
    | '/silos/$siloId/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/history'
    | '/new'
    | '/users'
    | '/'
    | '/documents/$documentId'
    | '/silos/$siloId/config'
    | '/silos/$siloId/new'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/history'
    | '/_app/new'
    | '/_app/users'
    | '/_app/'
    | '/_app/documents/$documentId'
    | '/_app/silos/$siloId/config'
    | '/_app/silos/$siloId/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new': {
      id: '/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/$documentId': {
      id: '/_app/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof AppDocumentsDocumentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/silos/$siloId/config': {
      id: '/_app/silos/$siloId/config'
      path: '/silos/$siloId/config'
      fullPath: '/silos/$siloId/config'
      preLoaderRoute: typeof AppSilosSiloIdConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/silos/$siloId/new': {
      id: '/_app/silos/$siloId/new'
      path: '/silos/$siloId/new'
      fullPath: '/silos/$siloId/new'
      preLoaderRoute: typeof AppSilosSiloIdNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppNewRoute: typeof AppNewRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDocumentsDocumentIdRoute: typeof AppDocumentsDocumentIdRoute
  AppSilosSiloIdConfigRoute: typeof AppSilosSiloIdConfigRoute
  AppSilosSiloIdNewRoute: typeof AppSilosSiloIdNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppNewRoute: AppNewRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppDocumentsDocumentIdRoute: AppDocumentsDocumentIdRoute,
  AppSilosSiloIdConfigRoute: AppSilosSiloIdConfigRoute,
  AppSilosSiloIdNewRoute: AppSilosSiloIdNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
